'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Finals_Final.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property barbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boy_in_hallway() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boy_in_hallway", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boy_in_his_room() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boy_in_his_room", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boy_with_his_classmate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boy_with_his_classmate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boy_with_his_teacher_natural_language_classmate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boy_with_his_teacher_natural_language_classmate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boy_with_teacher_in_research_classmate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boy_with_teacher_in_research_classmate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property campuscourtyard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campuscourtyard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Classroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Classroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property femaleroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("femaleroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property girl_hallway() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("girl_hallway", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property girl_in_her_room() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("girl_in_her_room", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property girl_teacher_in_research_classmate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("girl_teacher_in_research_classmate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property girl_teacher_natural_languange_classmate_comlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("girl_teacher_natural_languange_classmate_comlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property girl_with_her_classmate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("girl_with_her_classmate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property girl1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("girl1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hallway() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hallway", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainMenu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MainMenubgm() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MainMenubgm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mainmenufinal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mainmenufinal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainMenugif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenugif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mainmenupause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mainmenupause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property PressBtn() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("PressBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quizbook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quizbook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quizwallpeper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quizwallpeper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property recycle_bin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recycle_bin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property this_pc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("this_pc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s10comlabmalebff1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s10comlabmalebff1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s10female_friends() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s10female_friends", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s10profana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s10profana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s11bedroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s11bedroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s12onlydc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s12onlydc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s13maledc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s13maledc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s14bff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s14bff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s15malebffdc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s15malebffdc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s16classroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s16classroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s17classteacher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s17classteacher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s18malebffclassroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s18malebffclassroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s19classroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s19classroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s1hallway() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s1hallway", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s1schoolfrontfemale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s1schoolfrontfemale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s20courtyard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s20courtyard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s21malebff1courtyard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s21malebff1courtyard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s22malebff2courtyard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s22malebff2courtyard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s23bffcomlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s23bffcomlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s23malebffcourtyard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s23malebffcourtyard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s24malebffcourtyard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s24malebffcourtyard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s25malebffcourtyard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s25malebffcourtyard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s26malebffcourtyard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s26malebffcourtyard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s27malebffcourtyard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s27malebffcourtyard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s28comlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s28comlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s29comlabteacher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s29comlabteacher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s2hallwayfemale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s2hallwayfemale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s2hallwaymale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s2hallwaymale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s30malebffcomlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s30malebffcomlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s32comlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s32comlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s33bffcomlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s33bffcomlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s34malebffcomlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s34malebffcomlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s35teachercomlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s35teachercomlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s36malebffcomlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s36malebffcomlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s3schoolfront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s3schoolfront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s3schoolfrontfemale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s3schoolfrontfemale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s3schoolfrontfemalefriend1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s3schoolfrontfemalefriend1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s3schoolfrontfemalefriend2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s3schoolfrontfemalefriend2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s3schoolfrontfemalefriend3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s3schoolfrontfemalefriend3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s4comlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s4comlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s4femalefriend1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s4femalefriend1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s5comlabfemale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s5comlabfemale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s5schoolfrontmalefriends() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s5schoolfrontmalefriends", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s6femaleandfriend1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s6femaleandfriend1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s6femaleroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s6femaleroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s6femaleroomdiscord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s6femaleroomdiscord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s6schoolfrontmalefriends2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s6schoolfrontmalefriends2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s7classroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s7classroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s7femaleandfriend1classroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s7femaleandfriend1classroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s7schoolfrontmalefriends3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s7schoolfrontmalefriends3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s8female3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s8female3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s8female5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s8female5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s8femalefriend1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s8femalefriend1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s8femalefriend2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s8femalefriend2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s8femalefriend4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s8femalefriend4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s8schoolfrontmalefriends4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s8schoolfrontmalefriends4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s9comlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s9comlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s9female_friend1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s9female_friend1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s9femalefriend2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s9femalefriend2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y1s9profanacomlab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y1s9profanacomlab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd12maleschoolfront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd12maleschoolfront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd13maleclassroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd13maleclassroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd14girlcoffeeshop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd14girlcoffeeshop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd15girllibrary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd15girllibrary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd16malelibrary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd16malelibrary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd1girlbffclassroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd1girlbffclassroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd1malebffclassroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd1malebffclassroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd2girlbffcoffeshop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd2girlbffcoffeshop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd2malebffcoffeshop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd2malebffcoffeshop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd3girlbffschoolfront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd3girlbffschoolfront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd3malebffschoolfront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd3malebffschoolfront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd4girlbfflibrary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd4girlbfflibrary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd4malebfflibrary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd4malebfflibrary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd5bffclassroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd5bffclassroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd5girlbffclassroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd5girlbffclassroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd6girlbffcoffeeshop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd6girlbffcoffeeshop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd7girlbffschoolfront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd7girlbffschoolfront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd7malebfflibrary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd7malebfflibrary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd8girlbfflibrary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd8girlbfflibrary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd9girlbffcofeeshop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd9girlbffcofeeshop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y2nd9girlbffschoolfront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y2nd9girlbffschoolfront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y3female2bff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y3female2bff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property y3male2bff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y3male2bff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yr1s6femalefriend1roomdiscord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yr1s6femalefriend1roomdiscord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yr1s7profjaxclassroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yr1s7profjaxclassroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
